### ISSUE TITLE
Custom User Pickers user sort

### ISSUE THREAD

**Issue by endorphiner** [AndreyVMarkelov/mailru-jira-plugins-user-pickers#1]
Hi Andrey,

I have installed your plugin and it is really useful but the only issue that I am experiencing is that when you add groups to the field the users from the group are being sorted not in alphabetic order but visa versa. So instead of starting from A it is starting from Z. Is there any setting which can be used to change the sort order.

Thank you in advance.

P.S. Forgot to mention, I am using "Project Roles or Groups Multi User Picker" field type.

**Comment by AndreyVMarkelov** [comment]
Will be fixed during 3 days. Thanks

**Comment by AndreyVMarkelov** [comment]
Fixed in versions:
1.0.1 for JIRA 4.3.x-4.4.x
2.0.1 for JIRA 5.0.x-5.1.x
2.1.1 for JIRA 5.2.x

**Comment by AndreyVMarkelov** [comment]
Hi!

If you like this plug-In, please evaluate on marketplace:-)

-- Andrey
