### ISSUE TITLE
IE 8 Problem User Picker

### ISSUE THREAD

**Issue by andreasmaierde** [AndreyVMarkelov/mailru-jira-plugins-user-pickers#3]
Hello,

we use this Plug In (Version 2.0.13, JIRA Version 5.1.1) for short time and it is very useful. Great Job. 

At the moment, we have a Problem with the Internet Explorer 8, with Firefox or Chrome is it no problem.
When we use the field Group Multi User Pickers and use the option autocomplete , you can't  add user to the field. No search is running. See Screenshots

![hc_052](https://f.cloud.github.com/assets/5294334/1015884/c8d0a26c-0be9-11e3-822b-88bcccb67042.jpg)
![hc_055](https://f.cloud.github.com/assets/5294334/1015885/c97cd208-0be9-11e3-8426-92fd022bf04c.jpg)
![hc_054](https://f.cloud.github.com/assets/5294334/1015886/c97f1702-0be9-11e3-9984-1571b10d23ba.jpg)
![hc_053](https://f.cloud.github.com/assets/5294334/1015887/c9c1c174-0be9-11e3-8301-69fd38531f15.jpg)
![hc_056](https://f.cloud.github.com/assets/5294334/1015888/c9c86510-0be9-11e3-8ec0-f16dee36d375.jpg)

**Comment by Kienz** [comment]
@AndreyVMarkelov I have the same problem. IE8 doesn't support String.prototype.trim. http://kangax.github.io/es5-compat-table/#String.prototype.trim.
Maybe you can add a polyfill for that or using jQuery.trim():

```
if (!String.prototype.trim) {
  String.prototype.trim = function () {
    return this.replace(/^\s+|\s+$/g, '');
  };
}
```

https://github.com/AndreyVMarkelov/mailru-jira-plugins-user-pickers/blob/master/src/main/resources/media/mail-cf-up-autocomplete-lib.js#L48-49
https://github.com/AndreyVMarkelov/mailru-jira-plugins-user-pickers/blob/master/src/main/resources/media/mail-cf-up-autocomplete-lib.js#L71

Thanks a lot!

**Comment by AndreyVMarkelov** [comment]
Done

**Comment by Kienz** [comment]
@AndreyVMarkelov Thanks a lot!
